plotly/plotly.github.io

- _posts/2015-05-04-citation.md
Changes to make it visible at http://help.plot.ly/tutorials/
@mariahhamel, @chriddyp, @NicoleGrondin, @doeg
> Updated metadata

- _posts/2015-03-30-getting-data.md
Added free data urls, as per Jack's request. @jackparmer
> Added free data urls, as per Jack's request.

- _posts/2015-04-23-printing-and-sharing-graphs.md
Just a little text streamlining to match up with the images. @NicoleGrondin
> Small text changes.

- _includes/new_header.html
- _layouts/tutorials.html
- javascripts/scroll-menu.js
- stylesheets/layout_block.css
- stylesheets/modules.css
- stylesheets/state.css
closes #78
* add side-scroll-nav
* add caret to top-menu
* fix-up some css
> Add side scroll nav

- _posts/2015-05-20-how-to-color-points-of-a-scatter-plot-by-third-column.md
- _posts/2015-06-25-anova-test.md
Made edits on anova tutorial - ready to merge into master?
> Corinne anova tutorial

- _posts/2015-05-11-LaTeX-basics.md
Small, easy-to-proof tweaks to image names. @NicoleGrondin @doeg @chriddyp
> Edited text and images

- _posts/2015-04-23-chi-square-literacy.md
> Remove image and div around equations

- _includes/new_footer.html
- _layouts/excel-page.html
* add url query capacity
* set email_campaign_received to campaign_id
?campaign_id=chosenvalue
> Mixpanel update

- _includes/new_footer.html
mixpanel.register rather than mixpanel.register_once
> mixpanel correction

- _includes/meta-tutorial-links.html
> print button

- _posts/excel/3d Charts/2015-11-08-diamonds-scatter-plot-with-excel.md
Github gives me the build error, when I merge this branch to master. Probably because of using SSH keys to push commits. See [here](https://help.github.com/articles/troubleshooting-github-pages-build-failures/#unverified-email-address)
> Fixing Build Error

- _posts/2015-04-23-embed-plotly-graphs.md
> Fixed the links 

- _posts/2015-04-23-embed-plotly-graphs.md
edit embed tutorial screenshots
> edit screenshots

- _posts/2015-06-26-confidence-intervals.md
@yankev  Please help in merging this. 
cc @jackparmer
> modified-filled-error-bars

- _posts/2016-06-27-MariaDB.md
- _posts/2016-06-27-MsSQL.md
- _posts/2016-06-27-MySQL.md
- _posts/2016-06-27-Postgres.md
- _posts/2016-06-27-SQLlite.md
- _posts/2016-06-27-getting-started.md
minor copy edit cc @cldougl and @alexandresobolevski
> update sql tagline

- _data/cache_bust_css.yml
- index.html
- scss/_pages/_tutorial-index.scss
- styles/main.css
@cldougl added a couple small fixes! Could you review this and merge if it looks good?
Thanks!
cc: @jackparmer
> fixes mobile grid and added main.js to index.html

- _layouts/tutorials.html
- _posts/2015-04-21-bubble-chart.md
> index pg edits

- _posts/plotly2/how-to-add-a-logo-in-plotly2.md
> Added image tutorial doc

- _posts/plotly2/2016-08-12-how-to-add-annotations-in-plotly2.md
Hey, @cldougl. Do you like ramen?
> Annotations Tutorial

- _posts/plotly2/2016-09-22-how-to-make-an-area-chart.md
I'm missing two images that will be added after.
I can leave out those tiny sections for now (so we can add them to the page ASAP) or it'll have to be added once the issues have been closed.
> @cldougl Create Area Chart Doc

- _posts/plotly2/2019-09-21-shareplot-viewer-in-plotly2.md
> Shareplot Viewer doc ready

- _posts/plotly2/2016-06-23-how-to-enter-data.md
The last paragraph starting at "Working with multiple grids" isn't yet live on the site.
> Added keywords to the subtitle and metadescription

- _posts/plotly2/2016-06-23-how-to-save-export-and-share.md
Added keywords to the title, subtitle & metadescription
> Added SEO keywords

- _posts/plotly2/2016-06-28-how-to-create-a-stacked-bar-chart.md
Added SEO keywords to the title, subtitle and metadescriptions
Carried out small grammatical edits to the body copy
> SEO update + small copy edits

- _posts/plotly2/2016-06-28-how-to-make-a-grouped-bar-chart.md
Added keywords to the title, subtitle and metadescription
Carried out small, grammatical edits in the body text
> Added SEO keywords + small edits

- _posts/dashboards-spectacle/2016-11-11-add-website-to-dashboard.md
The "Not only can you add a [plot] and [text]..." section will include the mention of images, but once I update the text section in the "create a dashboard" doc.
> @cledougl doc review

- _includes/_new/_page-components/_header-main.html
rm dashboards.ly for dashboard/create
> update dashboard link

- _posts/connectors/2016-12-30-on-prem-login.md
fixes https://github.com/plotly/streambed/issues/9345
> Connector link fix

- _posts/fundamentals/2016-10-04-how-sharing-works.md
subscription privacy update
cc @chriddyp
> note about privacy change

- _posts/json/2015-11-06-json-chart-specification.md
missing "i" in "specification"
> fixed simple typo

- _posts/fundamentals/2018-08-13-on-premise-2-5-license-agreement.md
part of https://github.com/plotly/streambed/issues/11190
@scjody please review that this will be integrated properly to help.plot.ly/on-premise-2.5-license-agreement/
@sudburyrob please review content changes.
> add 2.5 license agreement

- _includes/_new/_page-components/_header-main.html
closes https://github.com/plotly/streambed/issues/11339
> Changed header to add DASH link

- _includes/_new/_page-components/_footer-main.html
- _includes/new_footer.html
partially addresses https://github.com/plotly/plotly-next/issues/159
> synced footer

- _layouts/tutorials.html
closes https://github.com/plotly/plotly.github.io/issues/377
> syncing trace types with plot.ly/create

- _layouts/tutorials.html
closes https://github.com/plotly/plotly.github.io/issues/376
> moving dashboards to bottom

- _includes/_new/_page-components/_footer-main.html
- styles/main.css
closes https://github.com/plotly/streambed/issues/11486
> Add Mailchimp form to footer

- _includes/google-tag-head.html
- static/images/getting-data/Data integrations.html
- static/images/getting-data/Data integrations_files/5821.html
addresses https://github.com/plotly/plotly-next/issues/210
> removing google ad

- _posts/fundamentals/2016-08-02-security.md
- static/images/getting-data/Data integrations.html
closes https://github.com/plotly/plotly.github.io/issues/390
> Remove marketing links

- 404.html
- _includes/_new/_page-components/_seo.html
- _includes/drift-tag.html
- _includes/head.html
- _includes/header.html
- _layouts/connectors-tutorial-single_layout.html
- _layouts/connectors.html
- _layouts/excel-page.html
- _layouts/excel-tutorial-single_layout.html
- _layouts/new_layout.html
- _layouts/search.html
- _layouts/single.html
- _layouts/tutorial-single_layout.html
- _layouts/tutorial.single.html
- _layouts/tutorials.html
- _layouts/two_column_layout.html
- index.html
- static/images/getting-data/Data integrations.html
addresses https://github.com/plotly/streambed/issues/12187
> adding drift to template pages

- _data/cache_bust_css.yml
- _includes/help-box.html
- scss/_components/_helpbox.scss
- styles/main.css
> adding dash anchor ad

- _posts/fundamentals/2016-10-04-how-sharing-works.md
fixes https://github.com/plotly/streambed/issues/12359
> fixes subscription typo

- _layouts/tutorials.html
closes https://github.com/plotly/plotly.github.io/issues/483
> changing the title

- _posts/fundamentals/2015-03-30-getting-data.md
> update getting data page to reflect changes in Chart Studio parsing

- _posts/fundamentals/2018-04-10-shareplot-viewer-in-plotly2.md
> fix viewplot markdown

- _posts/fundamentals/2015-04-23-embed-plotly-graphs.md
> add redirect from old embed link to embed tutorial

- _data/cache_bust_css.yml
- _includes/_new/_page-components/_header-main.html
- index.html
- package-lock.json
- scss/_components/_header.scss
- scss/_pages/_home.scss
- styles/main.css
closes https://github.com/plotly/plotly.github.io/issues/501
> Replace hero background 

- _includes/_new/_page-components/_footer-main.html
- scss/_components/_foot.scss
- styles/main.css
closes https://github.com/plotly/plotly.github.io/issues/502
> syncying footer urls with plotly-next

- _includes/new_footer.html
relates to: https://github.com/plotly/marketing-team/issues/118
> remove Google Analytics script

- _includes/_new/_page-components/_header-main.html
closes https://github.com/plotly/plotly.github.io/issues/528
> modify demo url
